# PowerShell script to fix project errors in MrComic

Write-Host "🔧 Исправление ошибок проекта MrComic..."

# Create missing consumer-rules.pro files
Write-Host "📝 Создание отсутствующих consumer-rules.pro файлов..."

$modules = @("core-analytics", "feature-themes", "core-domain")

foreach ($module in $modules) {
    $filePath = "android\$module\consumer-rules.pro"
    if (-not (Test-Path $filePath)) {
        "# Consumer ProGuard rules for $module" > $filePath
        "# Add module-specific ProGuard rules here" >> $filePath
        Write-Host "✅ Создан $filePath"
    }
}

# Fix Lint errors in build.gradle.kts files
Write-Host "🔧 Исправление Lint ошибок..."

# Function to add lint configuration to build.gradle.kts
function Add-LintConfig {
    param(
        [string]$file
    )
    
    if (Test-Path $file) {
        $content = Get-Content $file -Raw
        if (-not $content.Contains("lint {")) {
            # Add lint configuration after android { block
            $newContent = $content -replace "android \{", "android {
    lint {
        disable += ""NullSafeMutableLiveData""
    }"
            Set-Content $file $newContent
            Write-Host "✅ Добавлена lint конфигурация в $file"
        } else {
            Write-Host "ℹ️  Lint конфигурация уже существует в $file"
        }
    }
}

# Add lint configuration to all modules
$androidModules = @("app", "core", "core-analytics", "core-data", "core-domain", "core-model", "core-reader", "core-ui", "feature-library", "feature-ocr", "feature-onboarding", "feature-reader", "feature-settings", "feature-themes", "shared")

foreach ($module in $androidModules) {
    $buildFile = "android\$module\build.gradle.kts"
    if (Test-Path $buildFile) {
        Add-LintConfig -file $buildFile
    }
}

# Fix BookmarkEntity - add index
Write-Host "🗄️  Исправление BookmarkEntity..."

$bookmarkFile = "android\core-data\src\main\java\com\example\core\data\database\BookmarkEntity.kt"
if (Test-Path $bookmarkFile) {
    $content = Get-Content $bookmarkFile -Raw
    
    # Add import Index
    if (-not $content.Contains("import androidx.room.Index")) {
        $content = $content -replace "import androidx.room.ForeignKey", "import androidx.room.ForeignKey`nimport androidx.room.Index"
        Set-Content $bookmarkFile $content
    }
    
    # Add index to Entity annotation
    if (-not $content.Contains("indices = [Index")) {
        $content = $content -replace "foreignKeys = \[", "foreignKeys = [`n    ],`n    indices = [`n        Index(value = [""comicId""])`n    ]"
        $content = $content -replace "\],`n    indices = \[", ",`n    indices = ["
        Set-Content $bookmarkFile $content
    }
    
    Write-Host "✅ Исправлен BookmarkEntity с добавлением индекса"
}

# Fix deprecated Divider to HorizontalDivider
Write-Host "🎨 Исправление устаревших Divider..."

# Files to fix
$dividerFiles = @(
    "android\feature-settings\src\main\java\com\example\feature\settings\ui\SettingsScreen.kt",
    "android\feature-library\src\main\java\com\example\feature\library\ui\LibraryScreen.kt"
)

foreach ($file in $dividerFiles) {
    if (Test-Path $file) {
        (Get-Content $file) -replace "Divider\(", "HorizontalDivider(" | Set-Content $file
        Write-Host "✅ Исправлен $file"
    }
}

# Create .gitignore for build directories
Write-Host "📁 Создание .gitignore..."

if (-not (Test-Path ".gitignore")) {
    @(
        "# Built application files",
        "*.apk",
        "*.aar",
        "*.ap_",
        "*.aab",
        "",
        "# Files for the ART/Dalvik VM",
        "*.dex",
        "",
        "# Java class files",
        "*.class",
        "",
        "# Generated files",
        "bin/",
        "gen/",
        "out/",
        "#  Uncomment the following line in case you need and you don't have the release build type files in your app",
        "# release/",
        "",
        "# Gradle files",
        ".gradle/",
        "build/",
        "",
        "# Local configuration file (sdk path, etc)",
        "local.properties",
        "",
        "# Proguard folder generated by Eclipse",
        "proguard/",
        "",
        "# Log Files",
        "*.log",
        "",
        "# Android Studio Navigation editor temp files",
        ".navigation/",
        "",
        "# Android Studio captures folder",
        "captures/",
        "",
        "# IntelliJ",
        "*.iml",
        ".idea/workspace.xml",
        ".idea/tasks.xml",
        ".idea/gradle.xml",
        ".idea/assetWizardSettings.xml",
        ".idea/dictionaries",
        ".idea/libraries",
        "# Android Studio 3 in .gitignore file.",
        ".idea/caches",
        ".idea/modules.xml",
        "# Comment next line if keeping position of elements in Navigation Editor is desired for your project",
        ".idea/navEditor.xml",
        "",
        "# Keystore files",
        "# Uncomment the following lines if you do not want to check your keystore files in.",
        "#*.jks",
        "#*.keystore",
        "",
        "# External native build folder generated in Android Studio 2.2 and later",
        ".externalNativeBuild",
        ".cxx/",
        "",
        "# Google Services (e.g. APIs or Firebase)",
        "# google-services.json",
        "",
        "# Freeline",
        "freeline.py",
        "freeline/",
        "freeline_project_description.json",
        "",
        "# fastlane",
        "fastlane/report.xml",
        "fastlane/Preview.html",
        "fastlane/screenshots",
        "fastlane/test_output",
        "fastlane/readme.md",
        "",
        "# Version control",
        "vcs.xml",
        "",
        "# lint",
        "lint/intermediates/",
        "lint/generated/",
        "lint/outputs/",
        "lint/tmp/",
        "# lint/reports/",
        "",
        "# Android Profiling",
        "*.hprof",
        "",
        "# Detekt",
        "reports/"
    ) | Set-Content .gitignore
    Write-Host "✅ Создан .gitignore"
}

Write-Host "🎉 Исправление завершено!"
Write-Host ""
Write-Host "📋 Следующие шаги:"
Write-Host "1. Запустите: ./gradlew clean"
Write-Host "2. Запустите: ./gradlew build"
Write-Host "3. Проверьте отчет: PROJECT_ERROR_ANALYSIS_REPORT.md"
Write-Host ""
Write-Host "⚠️  Примечание: Некоторые ошибки требуют ручного исправления:"
Write-Host "- Миграция с ExoPlayer на Media3"
Write-Host "- Исправление неиспользуемых параметров"
Write-Host "- Обновление устаревших API"