package io.leostrange.mrcomic.feature.reader.ui.components

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.webkit.WebViewAssetLoader
import io.leostrange.mrcomic.core.model.ReadingMode
import io.leostrange.mrcomic.core.ui.theme.ReadingPreset
import io.leostrange.mrcomic.feature.reader.ui.HtmlPageView

@Composable
fun TextContainer(
    html: String,
    baseUrl: String?,
    assetDocumentPath: String?,
    assetLoader: WebViewAssetLoader?,
    readingMode: ReadingMode,
    autoScrollSpeed: Float = 0f,
    onLeftTap: () -> Unit,
    onRightTap: () -> Unit,
    onCenterTap: () -> Unit,
    onTranslateSelection: (String) -> Unit,
    onDictionarySelection: (String) -> Unit,
    onExplainSelection: (String) -> Unit,
    onSaveQuoteSelection: (String) -> Unit,
    onHighlightSelection: (String) -> Unit = {},
    onTranslateChapter: () -> Unit = {},
    onCompareTranslations: (String) -> Unit = {},
    highlightsJs: String = "",
    onAnchorClick: (String) -> Unit = {},
    onInlineFootnote: (String) -> Unit = {},
    onVerticalBoundaryNavigation: (Int) -> Unit = {},
    onPagedLayoutPageCountChanged: (pageCount: Int, pageIndex: Int) -> Unit = { _, _ -> },
    pendingScrollToAnchor: String? = null,
    onConsumeScrollToAnchor: () -> Unit = {},
    pendingWebtoonSectionIndex: Int? = null,
    onConsumeWebtoonSection: () -> Unit = {},
    onTextWebtoonVisibleSectionChanged: (Int) -> Unit = {},
    fontSize: Int = 18,
    colorScheme: String = "DAY",
    readerPreset: ReadingPreset = ReadingPreset.CUSTOM,
    fontFamily: String = "Georgia",
    fontSourceUrl: String? = null,
    lineHeight: Float = 1.8f,
    letterSpacing: Float = 0f,
    wordSpacing: Float = 0f,
    paragraphSpacing: Float = 0.2f,
    textAlign: String = "left",
    bold: Boolean = false,
    contentTopInsetPx: Int = 8,
    contentBottomInsetPx: Int = 24,
    overrideTextColor: String? = null,
    overrideBackgroundColor: String? = null,
    overrideAccentColor: String? = null,
    translateActionLabel: String,
    dictionaryActionLabel: String,
    explainActionLabel: String,
    saveQuoteActionLabel: String,
    onRegisterPageTurner: ((Int) -> Unit) -> Unit = {},
    modifier: Modifier = Modifier
) {
    HtmlPageView(
        html = html,
        baseUrl = baseUrl,
        assetDocumentPath = assetDocumentPath,
        assetLoader = assetLoader,
        onLeftTap = onLeftTap,
        onRightTap = onRightTap,
        onCenterTap = onCenterTap,
        onTranslateSelection = onTranslateSelection,
        onDictionarySelection = onDictionarySelection,
        onExplainSelection = onExplainSelection,
        onSaveQuoteSelection = onSaveQuoteSelection,
        onHighlightSelection = onHighlightSelection,
        onTranslateChapter = onTranslateChapter,
        onCompareTranslations = onCompareTranslations,
        highlightsJs = highlightsJs,
        onAnchorClick = onAnchorClick,
        onInlineFootnote = onInlineFootnote,
        onVerticalBoundaryNavigation = onVerticalBoundaryNavigation,
        onPagedLayoutPageCountChanged = onPagedLayoutPageCountChanged,
        pendingScrollToAnchor = pendingScrollToAnchor,
        onConsumeScrollToAnchor = onConsumeScrollToAnchor,
        pendingWebtoonSectionIndex = pendingWebtoonSectionIndex,
        onConsumeWebtoonSection = onConsumeWebtoonSection,
        onTextWebtoonVisibleSectionChanged = onTextWebtoonVisibleSectionChanged,
        readingMode = readingMode,
        autoScrollSpeed = autoScrollSpeed,
        fontSize = fontSize,
        colorScheme = colorScheme,
        readerPreset = readerPreset,
        fontFamily = fontFamily,
        fontSourceUrl = fontSourceUrl,
        lineHeight = lineHeight,
        letterSpacing = letterSpacing,
        wordSpacing = wordSpacing,
        paragraphSpacing = paragraphSpacing,
        textAlign = textAlign,
        bold = bold,
        contentTopInsetPx = contentTopInsetPx,
        contentBottomInsetPx = contentBottomInsetPx,
        overrideTextColor = overrideTextColor,
        overrideBackgroundColor = overrideBackgroundColor,
        overrideAccentColor = overrideAccentColor,
        translateActionLabel = translateActionLabel,
        dictionaryActionLabel = dictionaryActionLabel,
        explainActionLabel = explainActionLabel,
        saveQuoteActionLabel = saveQuoteActionLabel,
        onRegisterPageTurner = onRegisterPageTurner,
        modifier = modifier
    )
}
